---
language: node_js
node_js:
    - "iojs-v2.5"
    - "0.12"
    - "4.1"
branches:
    except:
        - circleci
sudo: false
notifications:
    email: false
cache:
    directories:
        - node_modules
matrix:
    fast_finish: true
services:
    - mongodb
    - redis-server
before_install:
    - npm install -g gulp livescript mocha node-gyp
    - npm install coveralls
before_script:
    - gulp build
    - redis-cli config set requirepass test
    - mongo lissome --eval "db.addUser('travis', 'test');"
    - node lib/commandline/setupschool.js
script:
    - npm run-script testCi
after_success:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
