language: node_js

node_js:
  - '0.10'
  - '0.11'

cache:
  directories:
    - node_modules

matrix:
  allow_failures:
    - node_js: '0.8'
    - node_js: '0.11'

before_install:
  - npm install coveralls

script:
  - npm run-script testCi

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: heroku
  on:
    node: '0.10'
  app:
    master: smrtboard
    develop: develop-smrtboard
  api_key:
    secure: TEvZYGO5uTcSU9QY0MeKbxfCGNWIbp9qaKrJ8GkDEJPNcyuLlV8b78PyBp0BsQgJ+uSkFl/ijL0wWIJRbjk97tBZAtJZkJIPKzaC8ovYGyDHSZoQdVtYYy5SgTYyUpUuFwUC3mQhFnoikinjYWenXFfRTeiir62kJdVKk0Kcj2E=
  skip_cleanup: true
