---
language: node_js
node_js:
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
branches:
    except:
        - circleci
sudo: false
notifications:
    email: false
cache:
    directories:
        - node_modules
matrix:
    fast_finish: true
services:
    - mongodb
    - redis-server
before_install:
    - npm install -g npm
    - npm install coveralls
before_script:
    - gulp build
    - redis-cli config set requirepass test
    - mongo lissome --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
    - node lib/commandline/setupschool.js
script:
    - npm run-script testCi
after_success:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
