---
language: node_js
node_js:
    - "iojs-v1.0"
    - "iojs-v3.0"
    - "0.10"
    - "0.12"
sudo: false
notifications:
    email: false
cache:
    directories:
        - node_modules
matrix:
    fast_finish: true
services:
    - mongodb
    - redis-server
before_install:
    - npm install coveralls
before_script:
    - gulp build
    - redis-cli config set requirepass test
    - mongo lissome --eval "db.addUser('travis', 'test');"
    - node lib/commandline/setupschool.js
script:
    - npm run-script testCi
after_success:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
