language: node_js

node_js:
  - '0.10'
  - '0.11'

cache:
  directories:
    - node_modules

matrix:
  allow_failures:
    - node_js: "0.11"

addons:
  code_climate:
    repo_token: b11d4cd7cfd91b5ce93a3442e422300e77caece4c4caf5ddfb35af85dd82c00a

script:
  - npm run-script testTravis

# after_script:
#   - cat coverage/lcov.info | codeclimate
